// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Alfajor struct {
	ID          string
	Name        string
	Relleno     string
	Cobertura   string
	Precio      int32
	Tapas       sql.NullInt32
	Marca       sql.NullString
	Descripcion sql.NullString
}

type Review struct {
	IDAlfajor    string
	IDUser       int32
	Calificacion sql.NullString
	Comentario   sql.NullString
	Fecha        sql.NullTime
}

type Usuario struct {
	ID    int32
	Name  string
	Email string
}
