// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAlfajor = `-- name: CreateAlfajor :one
INSERT INTO alfajor (id, name, relleno, cobertura, precio, tapas, marca, descripcion)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, relleno, cobertura, precio, tapas, marca, descripcion
`

type CreateAlfajorParams struct {
	ID          string
	Name        string
	Relleno     string
	Cobertura   string
	Precio      int32
	Tapas       sql.NullInt32
	Marca       sql.NullString
	Descripcion sql.NullString
}

func (q *Queries) CreateAlfajor(ctx context.Context, arg CreateAlfajorParams) (Alfajor, error) {
	row := q.db.QueryRowContext(ctx, createAlfajor,
		arg.ID,
		arg.Name,
		arg.Relleno,
		arg.Cobertura,
		arg.Precio,
		arg.Tapas,
		arg.Marca,
		arg.Descripcion,
	)
	var i Alfajor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Relleno,
		&i.Cobertura,
		&i.Precio,
		&i.Tapas,
		&i.Marca,
		&i.Descripcion,
	)
	return i, err
}

const deleteAlfajor = `-- name: DeleteAlfajor :exec
DELETE FROM alfajor
WHERE id = $1
`

func (q *Queries) DeleteAlfajor(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAlfajor, id)
	return err
}

const getAlfajor = `-- name: GetAlfajor :one
SELECT id, name, relleno, cobertura, precio, tapas, marca, descripcion
FROM alfajor
WHERE id = $1
`

func (q *Queries) GetAlfajor(ctx context.Context, id string) (Alfajor, error) {
	row := q.db.QueryRowContext(ctx, getAlfajor, id)
	var i Alfajor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Relleno,
		&i.Cobertura,
		&i.Precio,
		&i.Tapas,
		&i.Marca,
		&i.Descripcion,
	)
	return i, err
}

const listAlfajores = `-- name: ListAlfajores :many
SELECT id, name, relleno, cobertura, precio, tapas, marca, descripcion
FROM alfajor
ORDER BY name
`

func (q *Queries) ListAlfajores(ctx context.Context) ([]Alfajor, error) {
	rows, err := q.db.QueryContext(ctx, listAlfajores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alfajor
	for rows.Next() {
		var i Alfajor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Relleno,
			&i.Cobertura,
			&i.Precio,
			&i.Tapas,
			&i.Marca,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlfajor = `-- name: UpdateAlfajor :one
UPDATE alfajor
SET	name = $2,
	relleno = $3,
	cobertura = $4,
	precio = $5,
	tapas = $6,
	marca = $7,
	descripcion = $8
WHERE id = $1
RETURNING id, name, relleno, cobertura, precio, tapas, marca, descripcion
`

type UpdateAlfajorParams struct {
	ID          string
	Name        string
	Relleno     string
	Cobertura   string
	Precio      int32
	Tapas       sql.NullInt32
	Marca       sql.NullString
	Descripcion sql.NullString
}

func (q *Queries) UpdateAlfajor(ctx context.Context, arg UpdateAlfajorParams) (Alfajor, error) {
	row := q.db.QueryRowContext(ctx, updateAlfajor,
		arg.ID,
		arg.Name,
		arg.Relleno,
		arg.Cobertura,
		arg.Precio,
		arg.Tapas,
		arg.Marca,
		arg.Descripcion,
	)
	var i Alfajor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Relleno,
		&i.Cobertura,
		&i.Precio,
		&i.Tapas,
		&i.Marca,
		&i.Descripcion,
	)
	return i, err
}
